# Generated by Django 6.0.3 on 2026-04-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSize',
            new_name='ProductSizes',
        ),
    ]
