# Generated by Django 6.0.3 on 2026-04-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_productsize_productsizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSizes',
            new_name='ProductSize',
        ),
    ]
